version: "3.9"

services:
  anvil1:
    build:
      context: .
    ports:
      - "8545:8545"
    environment:
      CHAIN_ID: 31337
    restart: unless-stopped

  anvil2:
    build:
      context: .
    ports:
      - "8546:8545"
    environment:
      CHAIN_ID: 31338
    restart: unless-stopped
